# Generated by Django 3.2.13 on 2022-04-29 07:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='preview text'),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_text_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='preview text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ro',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
