version: "3.8"

services:
  db:
    container_name: testing-centers-db
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - "5445:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  api:
    container_name: testing-centers-api
    build:
      context: ./api
    command: dockerize -wait tcp://db:5444 -timeout 90s
    env_file:
      - .env
    volumes:
      - ./api:/code
    ports:
      - "8050:8050"
    depends_on:
      - db

  client:
    container_name: testing-centers-client
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - ./client:/code
    ports:
      - "3050:3000"
    depends_on:
      - api

volumes:
  pgdata:
    name: testing_centers-pgdata
