version: "3.8"

services:
  db:
    container_name: testing-centers-db
    build:
      context: ./db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  cache:
    container_name: testing-centers-cache
    image: memcached:1.6.14-alpine
    networks:
      - internal

  api:
    container_name: testing-centers-api
    build:
      context: ./api
      args:
        - ENVIRONMENT=production
    command: dockerize -wait tcp://db:5444 -timeout 90s
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./api:/code
    ports:
      - "8050:8050"
    depends_on:
      - db
      - cache

  client:
    container_name: testing-centers-client
    build:
      context: ./client
      args:
        - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - ./client:/code
    ports:
      - "3050:3000"
    depends_on:
      - api

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    name: testing_centers-pgdata
