# Generated by Django 3.2.11 on 2022-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterTestTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=200, unique=True, verbose_name='test type')),
                ('name_ro', models.CharField(default='', max_length=200, unique=True, verbose_name='tip de test')),
            ],
            options={
                'verbose_name': 'test type',
                'verbose_name_plural': 'test types',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('status', models.SmallIntegerField(choices=[(0, 'Not tried'), (1, 'Imported successfully'), (-1, 'Import failed')], default=0, editable=False, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Data file',
                'verbose_name_plural': 'Data files',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_caravans', models.IntegerField(null=True, verbose_name='mobile caravans')),
                ('hotline', models.SmallIntegerField(null=True, verbose_name='hotline')),
            ],
            options={
                'verbose_name': 'statistic',
                'verbose_name_plural': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='TestingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], db_index=True, default=0, verbose_name='status')),
                ('street_number', models.CharField(max_length=100, verbose_name='street number')),
                ('street_name', models.CharField(max_length=250, verbose_name='street name')),
                ('county', models.CharField(max_length=60, verbose_name='county')),
                ('locality', models.CharField(max_length=60, verbose_name='locality')),
                ('full_address', models.CharField(max_length=470, verbose_name='full address')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='website')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number')),
                ('schedule', models.CharField(blank=True, max_length=20, null=True, verbose_name='schedule')),
                ('test_types', models.ManyToManyField(blank=True, to='centers.CenterTestTypes', verbose_name='test types')),
            ],
        ),
    ]
