# Generated by Django 3.2.12 on 2022-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_centeremail_centerphonenumber_centerrating_centertesttypes_centertype_datafile_necessarydocuments_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTestingConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='type of condition')),
                ('name_ro', models.CharField(max_length=300, null=True, unique=True, verbose_name='type of condition')),
                ('name_en', models.CharField(max_length=300, null=True, unique=True, verbose_name='type of condition')),
            ],
            options={
                'verbose_name': 'free testing condition',
                'verbose_name_plural': 'free testing conditions',
            },
        ),
        migrations.AlterModelOptions(
            name='testingcenter',
            options={'verbose_name': 'testing center', 'verbose_name_plural': 'testing centers'},
        ),
        migrations.RemoveField(
            model_name='testingcenter',
            name='post_testing_counseling_conditions',
        ),
        migrations.RemoveField(
            model_name='testingcenter',
            name='pre_testing_counseling_conditions',
        ),
        migrations.AddField(
            model_name='testingcenter',
            name='post_testing_counseling_conditions',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Other'), (0, 'Face to face'), (1, 'Email'), (2, 'Phone'), (3, 'Mail'), (4, 'Platform')], default=-1, null=True, verbose_name='post-test counseling conditions'),
        ),
        migrations.AddField(
            model_name='testingcenter',
            name='pre_testing_counseling_conditions',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Other'), (0, 'Face to face'), (1, 'Email'), (2, 'Phone'), (3, 'Mail'), (4, 'Platform')], default=-1, null=True, verbose_name='pre-test counseling conditions'),
        ),
        migrations.RemoveField(
            model_name='testingcenter',
            name='free_testing_conditions',
        ),
        migrations.AddField(
            model_name='testingcenter',
            name='free_testing_conditions',
            field=models.ManyToManyField(blank=True, related_name='centers', to='centers.FreeTestingConditions'),
        ),
    ]
