# Generated by Django 3.2.12 on 2022-02-12 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_centerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerrating',
            name='rating',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
    ]
