# Generated by Django 3.2.12 on 2022-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20220408_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingcenter',
            name='testing_price',
            field=models.FloatField(blank=True, null=True, verbose_name='testing price'),
        ),
    ]
