# Generated by Django 3.2.12 on 2022-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_auto_20220414_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CenterRatingQuestions',
            new_name='CenterRatingQuestion',
        ),
    ]
