# Generated by Django 3.2.13 on 2022-04-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmailReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('status', models.SmallIntegerField(choices=[(0, 'Unsent'), (1, 'Sent')], db_index=True, default=0, verbose_name='email reminder status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule')),
            ],
            options={
                'verbose_name': 'contact email reminders',
                'verbose_name_plural': 'contact email reminders',
            },
        ),
    ]
