# Generated by Django 3.2.11 on 2022-02-04 19:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Page title', max_length=150, verbose_name='title')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL slug (leave empty to auto-generate)', max_length=150, unique=True, verbose_name='slug')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Last update time', null=True, verbose_name='updated on')),
                ('publishing_date', models.DateTimeField(blank=True, help_text='Public page publishing date', null=True, verbose_name='publishing date')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Is this page visible on the website', verbose_name='is published')),
                ('category', models.ForeignKey(blank=True, help_text='Page category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attachment name', max_length=150, verbose_name='name')),
                ('upload_date', models.DateTimeField(auto_now=True, help_text='Attachment upload date', verbose_name='upload date')),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='uploaded file')),
                ('page', models.ForeignKey(blank=True, help_text='Page attachment', on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='attachment')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
    ]
